[package]
name = "ndspectral"
version = "0.1.0"
authors = ["preiter <phil.reiter93@gmail.com>"]
edition = "2018"
description = "N-dimensional spectral transforms of various basis functions"

[dependencies]
ndarray = { version = "0.15.0", features = ["rayon"] }
#ndarray-linalg = { version = "0.13", features = ["openblas-static"]}
ndrustfft = "0.1.0"
enum_dispatch = "0.3.7"
num-traits = "0.2.12"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[lib]
name = "ndspectral"
path = "src/lib.rs"
